version: '3.3'

services:
  app:
    build:
      context: . # プロジェクトのルートディレクトリを指定
      dockerfile: ./backend//Dockerfile # Dockerfileへの相対パス
    volumes:
      - .:/workspace:cached
    command: uvicorn main:app --reload --reload-dir /workspace/backend --host 0.0.0.0 --port 8000
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "8000:8000"
